const SERVICE_ASSETS = '/services';

export const SERVICE_CATALOG = [
  {
    slug: 'trong-rang-implant',
    name: 'Trồng răng Implant',
    shortName: 'Implant',
    image: `${SERVICE_ASSETS}/implant.webp`,
    summary: 'Phục hồi răng mất bằng trụ Implant, hỗ trợ ăn nhai chắc chắn và giữ thẩm mỹ nụ cười.',
    intro: 'Giải pháp Implant phù hợp cho khách hàng mất một răng, nhiều răng hoặc cần phục hồi lâu dài với cảm giác ăn nhai ổn định hơn.',
    benefits: ['Khôi phục khả năng ăn nhai', 'Hạn chế tiêu xương vùng mất răng', 'Không mài răng kế cận'],
    process: ['Thăm khám và chụp phim', 'Lên kế hoạch đặt trụ', 'Phục hình mão sứ sau khi tích hợp'],
  },
  {
    slug: 'tram-rang-composite',
    name: 'Trám răng Composite',
    shortName: 'Composite',
    image: `${SERVICE_ASSETS}/tram-rang-composite.webp`,
    summary: 'Khôi phục mô răng sâu, mẻ hoặc thưa nhỏ bằng vật liệu có màu gần với răng thật.',
    intro: 'Trám Composite giúp xử lý tổn thương nhỏ trên răng trong thời gian ngắn, giữ hình thể răng gọn gàng và tự nhiên.',
    benefits: ['Thực hiện nhanh', 'Màu sắc hài hòa', 'Bảo tồn mô răng tối đa'],
    process: ['Làm sạch vùng răng cần trám', 'Tạo hình Composite', 'Chiếu đèn và đánh bóng'],
  },
  {
    slug: 'chinh-nha-nieng-rang',
    name: 'Chỉnh nha - Niềng răng',
    shortName: 'Niềng răng',
    image: `${SERVICE_ASSETS}/nieng-rang.webp`,
    summary: 'Điều chỉnh răng lệch lạc, chen chúc hoặc sai khớp cắn bằng kế hoạch chỉnh nha rõ ràng.',
    intro: 'Chỉnh nha tại iSmile tập trung vào chẩn đoán kỹ, theo dõi định kỳ và giúp khách hàng hiểu rõ từng giai đoạn dịch chuyển răng.',
    benefits: ['Cải thiện khớp cắn', 'Tăng thẩm mỹ khuôn mặt', 'Theo dõi tiến trình định kỳ'],
    process: ['Khám và lấy dữ liệu chỉnh nha', 'Gắn mắc cài hoặc khí cụ', 'Tái khám và tinh chỉnh lực kéo'],
  },
  {
    slug: 'dinh-da-rang',
    name: 'Đính đá răng',
    shortName: 'Đính đá',
    image: `${SERVICE_ASSETS}/dinh-da-rang.webp`,
    summary: 'Tạo điểm nhấn thẩm mỹ nhỏ trên răng với quy trình gọn, sạch và được kiểm soát kỹ.',
    intro: 'Đính đá răng phù hợp với khách hàng muốn tạo điểm nhấn cá nhân cho nụ cười mà vẫn giữ bề mặt răng được chăm sóc cẩn thận.',
    benefits: ['Tăng điểm nhấn nụ cười', 'Quy trình nhanh', 'Tư vấn vị trí phù hợp trước khi thực hiện'],
    process: ['Kiểm tra bề mặt răng', 'Chọn vị trí và kiểu đá', 'Gắn cố định và hướng dẫn chăm sóc'],
  },
  {
    slug: 'dan-su-veneer',
    name: 'Dán sứ Veneer',
    shortName: 'Veneer',
    image: `${SERVICE_ASSETS}/dan-su-veneer.webp`,
    summary: 'Cải thiện màu sắc và hình thể răng bằng mặt dán sứ mỏng, thiên về thẩm mỹ tự nhiên.',
    intro: 'Veneer là lựa chọn cho các trường hợp răng xỉn màu, thưa nhẹ hoặc cần điều chỉnh hình dáng nhưng vẫn ưu tiên bảo tồn mô răng.',
    benefits: ['Thẩm mỹ tự nhiên', 'Mài răng ít hơn mão sứ', 'Cá nhân hóa dáng răng'],
    process: ['Tư vấn dáng răng', 'Chuẩn bị bề mặt răng', 'Gắn mặt dán và kiểm tra khớp cắn'],
  },
  {
    slug: 'nha-khoa-tre-em',
    name: 'Nha khoa trẻ em',
    shortName: 'Trẻ em',
    image: `${SERVICE_ASSETS}/nha-khoa-tre-em.webp`,
    summary: 'Thăm khám, phòng ngừa và điều trị răng miệng cho bé trong không khí nhẹ nhàng.',
    intro: 'Dịch vụ nha khoa trẻ em giúp bé làm quen với phòng khám, phát hiện sớm vấn đề răng miệng và hình thành thói quen chăm sóc răng tốt.',
    benefits: ['Khám nhẹ nhàng cho bé', 'Theo dõi răng sữa và răng vĩnh viễn', 'Tư vấn chăm sóc tại nhà'],
    process: ['Khám tổng quát', 'Tư vấn cho phụ huynh', 'Điều trị hoặc phòng ngừa theo chỉ định'],
  },
  {
    slug: 'ham-thao-lap',
    name: 'Hàm tháo lắp',
    shortName: 'Hàm tháo lắp',
    image: `${SERVICE_ASSETS}/ham-thao-lap.webp`,
    summary: 'Phục hồi răng mất bằng hàm tháo lắp, phù hợp với nhiều nhu cầu và điều kiện điều trị.',
    intro: 'Hàm tháo lắp hỗ trợ ăn nhai và thẩm mỹ cho khách hàng mất nhiều răng, đặc biệt khi cần một phương án linh hoạt hơn.',
    benefits: ['Chi phí linh hoạt', 'Dễ tháo lắp vệ sinh', 'Phù hợp nhiều tình trạng mất răng'],
    process: ['Khám và lấy dấu hàm', 'Thiết kế hàm phù hợp', 'Giao hàm và chỉnh khớp cắn'],
  },
  {
    slug: 'tram-rang-tham-my',
    name: 'Trám răng thẩm mỹ',
    shortName: 'Trám thẩm mỹ',
    image: `${SERVICE_ASSETS}/tram-rang-tham-my.webp`,
    summary: 'Xử lý khuyết điểm nhỏ trên răng trước với vật liệu thẩm mỹ, giữ nụ cười đều hơn.',
    intro: 'Trám thẩm mỹ tập trung vào vùng răng dễ thấy, đòi hỏi tạo hình kỹ và màu sắc hòa hợp với răng thật.',
    benefits: ['Cải thiện răng mẻ/thưa nhỏ', 'Màu sắc tự nhiên', 'Không cần can thiệp quá sâu'],
    process: ['Tư vấn màu và hình thể', 'Tạo hình vật liệu trám', 'Hoàn thiện và đánh bóng'],
  },
  {
    slug: 'dieu-tri-chuyen-sau',
    name: 'Điều trị chuyên sâu',
    shortName: 'Chuyên sâu',
    image: `${SERVICE_ASSETS}/dieu-tri-chuyen-sau.webp`,
    summary: 'Thăm khám và xử lý các vấn đề răng miệng cần bác sĩ theo dõi kỹ từng bước.',
    intro: 'Nhóm điều trị chuyên sâu dành cho các tình trạng cần chẩn đoán rõ, tư vấn lộ trình và theo dõi sát trong quá trình điều trị.',
    benefits: ['Chẩn đoán kỹ', 'Lộ trình điều trị rõ', 'Theo dõi sau điều trị'],
    process: ['Khám và đánh giá tình trạng', 'Lên kế hoạch điều trị', 'Tái khám theo chỉ định'],
  },
];

export function getServiceBySlug(slug) {
  return SERVICE_CATALOG.find((service) => service.slug === slug);
}
