/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const LANGUAGE_OPTIONS = [
  { code: 'vi', short: 'VI', label: 'Tiếng Việt' },
  { code: 'en', short: 'EN', label: 'English' },
  { code: 'ja', short: 'JA', label: '日本語' },
  { code: 'zh', short: 'ZH', label: '中文' },
  { code: 'fr', short: 'FR', label: 'Français' },
];

const translations = {
  vi: {
    nav: {
      home: 'Trang chủ',
      services: 'Dịch vụ',
      doctors: 'Đội ngũ',
      facility: 'Cơ sở',
      booking: 'Đặt lịch',
    },
    common: {
      hotline: 'Hotline',
      bookNow: 'Đặt lịch ngay',
      bookVisit: 'Đặt lịch khám',
      chooseSchedule: 'Chọn lịch ngay',
      contactUs: 'Kết nối với chúng tôi',
      address: 'Địa chỉ',
      phone: 'Điện thoại',
      email: 'Email',
      openingHours: 'Giờ mở cửa',
      themeLight: 'Giao diện sáng',
      themeDark: 'Giao diện tối',
      language: 'Ngôn ngữ',
    },
    hero: {
      badge: 'Nha khoa iSmile Dental Clinic',
      title: 'Chăm sóc nụ cười bằng sự rõ ràng, nhẹ nhàng và tận tâm.',
      desc: 'iSmile kết hợp bác sĩ theo sát, thiết bị hiện đại và hình ảnh thực tế để mỗi khách hàng an tâm hơn trước khi bắt đầu điều trị.',
      explore: 'Xem dịch vụ',
      promises: ['Thiết bị hiện đại', 'Tư vấn rõ lộ trình', 'Chăm sóc cá nhân hóa'],
      stats: [
        { value: '15+', label: 'năm kinh nghiệm' },
        { value: '5.000+', label: 'khách hàng' },
        { value: '30 phút', label: 'xác nhận lịch' },
      ],
    },
    campaign: {
      eyebrow: 'Hoạt động & phản hồi',
      title: 'Những khoảnh khắc thật làm nên niềm tin tại iSmile.',
      desc: 'Từ chương trình cộng đồng, ngày hội thiếu nhi đến feedback sau điều trị, mọi hình ảnh đều được đặt trong một trải nghiệm sáng và dễ theo dõi.',
      labels: {
        community: 'Cộng đồng',
        event: 'Sự kiện',
        feedback: 'Feedback',
        result: 'Trước / sau',
        space: 'Không gian',
        treatment: 'Điều trị',
      },
      moments: 'khoảnh khắc',
      chooseImage: 'Chọn ảnh',
      prev: 'Ảnh trước',
      next: 'Ảnh tiếp theo',
      pause: 'Tạm dừng carousel',
      play: 'Phát carousel',
      book: 'Đặt lịch tư vấn',
    },
    experience: {
      eyebrow: 'Trải nghiệm iSmile',
      title: 'Đặt lịch nhanh, thăm khám gọn và luôn biết bước tiếp theo.',
      desc: 'Từ tư vấn ban đầu đến xác nhận lịch hẹn, đội ngũ iSmile giữ quy trình rõ ràng để khách hàng thoải mái hơn khi đến phòng khám.',
      steps: [
        { title: 'Tư vấn tận tâm', desc: 'Lắng nghe nhu cầu trước khi đề xuất dịch vụ phù hợp.' },
        { title: 'Giữ lịch nhanh', desc: 'Chọn khung giờ phù hợp và xác nhận trong thời gian ngắn.' },
        { title: 'Điều trị rõ ràng', desc: 'Bác sĩ giải thích lộ trình, chi phí và thời gian thực hiện.' },
      ],
      quickAction: 'Hỗ trợ nhanh',
      quickTitle: 'Đặt lịch khám trong vài phút',
    },
    services: {
      eyebrow: 'Dịch vụ nổi bật',
      title: 'Giải pháp nha khoa được trình bày rõ ràng để bạn dễ chọn đúng nhu cầu.',
      featured: 'Điều trị tiêu biểu',
      contact: 'Liên hệ',
      from: 'Từ',
      million: 'triệu',
      bookThis: 'Đặt lịch dịch vụ này',
      book: 'Đặt lịch',
    },
    doctors: {
      eyebrow: 'Đội ngũ bác sĩ',
      title: 'Hai bác sĩ phụ trách chính, đồng hành sát với từng kế hoạch điều trị.',
      desc: 'Bác sĩ Lê Nhi và bác sĩ Anh Dũng trực tiếp tư vấn, theo dõi tiến trình và giữ sự thoải mái cho khách hàng trong từng lần hẹn.',
      experience: 'năm kinh nghiệm',
      bookWith: 'Đặt lịch với bác sĩ',
      choose: 'Chọn bác sĩ này',
      spotlight: 'Bác sĩ phụ trách',
    },
    facility: {
      eyebrow: 'Cơ sở vật chất',
      title: 'Không gian phòng khám sáng, sạch và được chuẩn bị kỹ cho từng ca điều trị.',
      desc: 'Hình ảnh thực tế giúp khách hàng nhìn rõ phòng điều trị, khu tiếp đón và thiết bị đang được sử dụng tại iSmile.',
      cards: [
        { title: 'Phòng điều trị hiện đại', desc: 'Thiết bị nhập khẩu, vô trùng nghiêm ngặt và quy trình gọn gàng.' },
        { title: 'Không gian tiếp đón', desc: 'Khu vực sáng sủa, sạch sẽ và thuận tiện cho khách hàng trước khi thăm khám.' },
        { title: 'Hình ảnh khách hàng thật', desc: 'Những khoảnh khắc tại iSmile giúp trải nghiệm thương hiệu gần gũi và đáng tin hơn.' },
      ],
      lobbyAlt: 'Không gian tổng thể Nha Khoa iSmile',
    },
    bookingPage: {
      steps: ['Điền thông tin', 'Chọn dịch vụ', 'Nhận xác nhận'],
      badge: 'Đặt lịch online',
      title: 'Chọn lịch hẹn phù hợp và để iSmile xác nhận nhanh cho bạn.',
      desc: 'Để lại thông tin cần thiết, đội ngũ iSmile sẽ liên hệ xác nhận thời gian và tư vấn bước chuẩn bị trước khi đến phòng khám.',
      privacy: 'Thông tin đặt lịch chỉ dùng để tư vấn và xác nhận lịch hẹn tại iSmile.',
    },
    bookingForm: {
      successTitle: 'Đặt lịch thành công!',
      successDesc: 'iSmile đã nhận thông tin. Đội ngũ tư vấn sẽ liên hệ xác nhận lịch hẹn trong thời gian sớm nhất.',
      another: 'Đặt lịch khác',
      eyebrow: 'Form đặt lịch',
      title: 'Thông tin hẹn khám',
      desc: 'Điền nhanh trong một lần, iSmile gọi lại xác nhận.',
      fullName: 'Họ và tên *',
      phone: 'Số điện thoại *',
      service: 'Dịch vụ',
      doctor: 'Bác sĩ',
      date: 'Ngày khám *',
      time: 'Giờ khám *',
      note: 'Ghi chú',
      servicePlaceholder: 'Chọn dịch vụ',
      doctorPlaceholder: 'Chọn bác sĩ',
      notePlaceholder: 'Mô tả triệu chứng hoặc yêu cầu đặc biệt...',
      sending: 'Đang gửi...',
      submit: 'Gửi yêu cầu đặt lịch',
      namePlaceholder: 'Nguyễn Văn A',
    },
    footer: {
      info: 'Thông tin về iSmile',
      services: 'Dịch vụ nha khoa',
      infoLinks: ['Dịch vụ nha khoa', 'Đội ngũ bác sĩ', 'Cơ sở vật chất', 'Đặt lịch khám'],
      serviceLinks: ['Trồng răng Implant', 'Nha khoa thẩm mỹ', 'Dán sứ veneer', 'Bọc răng sứ thẩm mỹ', 'Chỉnh nha - Niềng răng', 'Nha khoa trẻ em'],
    },
  },
  en: {
    nav: { home: 'Home', services: 'Services', doctors: 'Doctors', facility: 'Clinic', booking: 'Booking' },
    common: {
      hotline: 'Hotline',
      bookNow: 'Book now',
      bookVisit: 'Book a visit',
      chooseSchedule: 'Choose a time',
      contactUs: 'Connect with us',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      openingHours: 'Opening hours',
      themeLight: 'Light mode',
      themeDark: 'Dark mode',
      language: 'Language',
    },
    hero: {
      badge: 'iSmile Dental Clinic',
      title: 'Dental care that feels clear, gentle and personal.',
      desc: 'iSmile combines attentive doctors, modern equipment and real clinic imagery so every patient feels confident before treatment starts.',
      explore: 'View services',
      promises: ['Modern equipment', 'Clear treatment plan', 'Personalized care'],
      stats: [
        { value: '15+', label: 'years of experience' },
        { value: '5,000+', label: 'patients' },
        { value: '30 min', label: 'booking confirmation' },
      ],
    },
    campaign: {
      eyebrow: 'Campaign & Feedback',
      title: 'Real iSmile moments that build trust.',
      desc: 'Community programs, children’s events and treatment feedback are presented in a bright, easy-to-follow visual rhythm.',
      labels: { community: 'Community', event: 'Event', feedback: 'Feedback', result: 'Before / after', space: 'Space', treatment: 'Treatment' },
      moments: 'moments',
      chooseImage: 'Choose image',
      prev: 'Previous image',
      next: 'Next image',
      pause: 'Pause carousel',
      play: 'Play carousel',
      book: 'Book a consultation',
      typeCopy: {
        community: {
          kicker: 'Community program',
          title: 'Smile Revival program',
          desc: 'Support stories for older patients and people who need help restoring their bite and confidence.',
        },
        event: {
          kicker: 'Children event',
          title: 'Children Smile Day',
          desc: 'A bright clinic event with checkups, gifts and family-friendly dental care for kids.',
        },
        feedback: {
          kicker: 'Real patient feedback',
          title: 'A real iSmile moment',
          desc: 'Patient photos from the clinic help the website feel warmer, more natural and more trustworthy.',
        },
        result: {
          kicker: 'Treatment result',
          title: 'Before and after smile care',
          desc: 'A direct look at visible tooth shade improvement after aesthetic dental treatment.',
        },
        space: {
          kicker: 'Clinical space',
          title: 'Real treatment room',
          desc: 'A practical image of the clinic space and equipment used during patient care.',
        },
        treatment: {
          kicker: 'Conservative treatment',
          title: 'Gentle root canal care',
          desc: 'Communication materials that highlight careful consultation, modern technology and tooth preservation.',
        },
      },
    },
    experience: {
      eyebrow: 'iSmile Experience',
      title: 'Fast booking, clear visits and a team that guides each step.',
      desc: 'From the first consultation to appointment confirmation, iSmile keeps the process simple so patients feel comfortable before arriving.',
      steps: [
        { title: 'Thoughtful consultation', desc: 'We listen first, then suggest the most suitable service.' },
        { title: 'Quick scheduling', desc: 'Pick a convenient time and receive confirmation soon.' },
        { title: 'Transparent treatment', desc: 'Doctors explain the plan, cost and expected timeline.' },
      ],
      quickAction: 'Quick support',
      quickTitle: 'Book a dental visit in minutes',
    },
    services: {
      eyebrow: 'Featured Services',
      title: 'Dental solutions are presented clearly so you can choose with confidence.',
      featured: 'Featured treatment',
      contact: 'Contact us',
      from: 'From',
      million: 'million VND',
      bookThis: 'Book this service',
      book: 'Book',
    },
    doctors: {
      eyebrow: 'Doctor Team',
      title: 'Two lead doctors follow each treatment plan closely.',
      desc: 'Dr. Le Nhi and Dr. Anh Dung consult directly, monitor progress and keep every appointment comfortable.',
      experience: 'years of experience',
      bookWith: 'Book with doctor',
      choose: 'Choose this doctor',
      spotlight: 'Lead doctor',
    },
    facility: {
      eyebrow: 'Facilities',
      title: 'A bright, clean clinic prepared carefully for every treatment.',
      desc: 'Real images show the treatment rooms, reception area and equipment currently used at iSmile.',
      cards: [
        { title: 'Modern treatment room', desc: 'Imported equipment, strict sterilization and a tidy workflow.' },
        { title: 'Reception area', desc: 'A clean and convenient space for patients before their visit.' },
        { title: 'Real patient moments', desc: 'Clinic moments make the iSmile experience feel warmer and more trustworthy.' },
      ],
      lobbyAlt: 'iSmile Dental Clinic overview',
    },
    bookingPage: {
      steps: ['Your details', 'Choose service', 'Confirmation'],
      badge: 'Online booking',
      title: 'Choose a suitable appointment and let iSmile confirm it quickly.',
      desc: 'Leave the essential details and our team will confirm the time and advise what to prepare before your visit.',
      privacy: 'Booking information is used only for consultation and appointment confirmation at iSmile.',
    },
    bookingForm: {
      successTitle: 'Booking submitted!',
      successDesc: 'iSmile has received your information. Our team will contact you soon to confirm the appointment.',
      another: 'Book another appointment',
      eyebrow: 'Booking form',
      title: 'Appointment details',
      desc: 'Fill it once and iSmile will call back to confirm.',
      fullName: 'Full name *',
      phone: 'Phone number *',
      service: 'Service',
      doctor: 'Doctor',
      date: 'Visit date *',
      time: 'Visit time *',
      note: 'Note',
      servicePlaceholder: 'Choose a service',
      doctorPlaceholder: 'Choose a doctor',
      notePlaceholder: 'Describe symptoms or special requests...',
      sending: 'Sending...',
      submit: 'Send booking request',
      namePlaceholder: 'Your full name',
    },
    footer: {
      info: 'About iSmile',
      services: 'Dental services',
      infoLinks: ['Dental services', 'Doctor team', 'Facilities', 'Book a visit'],
      serviceLinks: ['Dental implants', 'Cosmetic dentistry', 'Porcelain veneers', 'Aesthetic crowns', 'Orthodontics', 'Children dentistry'],
    },
  },
  ja: {
    nav: { home: 'ホーム', services: '診療内容', doctors: '医師紹介', facility: '院内設備', booking: '予約' },
    common: {
      hotline: 'ホットライン',
      bookNow: '今すぐ予約',
      bookVisit: '診療予約',
      chooseSchedule: '日時を選ぶ',
      contactUs: 'お問い合わせ',
      address: '住所',
      phone: '電話',
      email: 'メール',
      openingHours: '診療時間',
      themeLight: 'ライトモード',
      themeDark: 'ダークモード',
      language: '言語',
    },
    hero: {
      badge: 'iSmile デンタルクリニック',
      title: 'わかりやすく、やさしく、一人ひとりに寄り添う歯科ケア。',
      desc: 'iSmileは丁寧な医師、先進設備、実際の院内写真で、治療前から安心できる体験を整えます。',
      explore: '診療を見る',
      promises: ['先進設備', '明確な治療計画', '個別ケア'],
      stats: [
        { value: '15+', label: '年の経験' },
        { value: '5,000+', label: '患者様' },
        { value: '30分', label: '予約確認' },
      ],
    },
    campaign: {
      eyebrow: 'キャンペーン & 声',
      title: '信頼につながるiSmileのリアルな瞬間。',
      desc: '地域支援、キッズイベント、治療後の声を明るく見やすい流れで紹介します。',
      labels: { community: '地域支援', event: 'イベント', feedback: '患者様の声', result: 'ビフォーアフター', space: '院内', treatment: '治療' },
      moments: 'シーン',
      chooseImage: '画像を選択',
      prev: '前の画像',
      next: '次の画像',
      pause: '一時停止',
      play: '再生',
      book: '相談予約',
      typeCopy: {
        community: {
          kicker: '地域支援プログラム',
          title: '笑顔を取り戻す取り組み',
          desc: '噛む力と自信の回復を必要とする方を支えるストーリーです。',
        },
        event: {
          kicker: 'キッズイベント',
          title: 'こどもスマイルデー',
          desc: '検診、プレゼント、家族向けの歯科ケアを明るく紹介します。',
        },
        feedback: {
          kicker: '患者様の声',
          title: 'iSmileでのリアルな瞬間',
          desc: '院内で撮影された写真が、より自然で信頼できる印象を届けます。',
        },
        result: {
          kicker: '治療結果',
          title: 'ビフォーアフター',
          desc: '審美歯科後の歯の色の変化をわかりやすく見せます。',
        },
        space: {
          kicker: '診療空間',
          title: '実際の治療室',
          desc: '患者様のケアで使われる院内設備と診療スペースの写真です。',
        },
        treatment: {
          kicker: '保存治療',
          title: 'やさしい根管治療',
          desc: '丁寧な相談、先進技術、歯を残す方針を伝える資料です。',
        },
      },
    },
    experience: {
      eyebrow: 'iSmile体験',
      title: '予約はスムーズ、来院はわかりやすく、次の流れも明確に。',
      desc: '初回相談から予約確認まで、iSmileはシンプルな流れで来院前の不安を減らします。',
      steps: [
        { title: '丁寧な相談', desc: 'まずご希望を伺い、合う診療を提案します。' },
        { title: 'すばやい予約', desc: '都合の良い時間を選び、早めに確認します。' },
        { title: '明確な治療', desc: '治療計画、費用、期間を医師が説明します。' },
      ],
      quickAction: 'クイックサポート',
      quickTitle: '数分で診療予約',
    },
    services: {
      eyebrow: '主な診療',
      title: '必要な治療を迷わず選べるよう、歯科サービスをわかりやすく整理しました。',
      featured: '注目治療',
      contact: 'お問い合わせ',
      from: '約',
      million: '百万VNDから',
      bookThis: 'この診療を予約',
      book: '予約',
    },
    doctors: {
      eyebrow: '医師チーム',
      title: '2名の担当医が、それぞれの治療計画にしっかり寄り添います。',
      desc: 'レ・ニー医師とアン・ズン医師が直接相談し、治療経過を確認しながら安心できる時間をつくります。',
      experience: '年の経験',
      bookWith: '医師を予約',
      choose: 'この医師を選ぶ',
      spotlight: '担当医',
    },
    facility: {
      eyebrow: '院内設備',
      title: '明るく清潔で、各治療に合わせて整えられたクリニック空間。',
      desc: '実際の写真で、治療室、受付、iSmileで使われている設備をご覧いただけます。',
      cards: [
        { title: '先進的な治療室', desc: '輸入設備、厳格な滅菌、整った診療フロー。' },
        { title: '受付スペース', desc: '来院前に過ごしやすい、清潔で便利な空間。' },
        { title: '患者様のリアルな瞬間', desc: 'iSmileでの表情が、より温かく信頼できる体験を伝えます。' },
      ],
      lobbyAlt: 'iSmileデンタルクリニック全景',
    },
    bookingPage: {
      steps: ['情報入力', '診療選択', '確認連絡'],
      badge: 'オンライン予約',
      title: 'ご希望の日時を選ぶと、iSmileがすばやく確認します。',
      desc: '必要事項を残していただければ、来院前の準備も含めてスタッフがご案内します。',
      privacy: '予約情報はiSmileでの相談と予約確認のみに使用されます。',
    },
    bookingForm: {
      successTitle: '予約を受け付けました。',
      successDesc: 'iSmileが情報を受け取りました。スタッフがまもなく確認の連絡をします。',
      another: '別の予約をする',
      eyebrow: '予約フォーム',
      title: '予約情報',
      desc: '一度入力すれば、iSmileが折り返し確認します。',
      fullName: 'お名前 *',
      phone: '電話番号 *',
      service: '診療',
      doctor: '医師',
      date: '来院日 *',
      time: '時間 *',
      note: 'メモ',
      servicePlaceholder: '診療を選択',
      doctorPlaceholder: '医師を選択',
      notePlaceholder: '症状やご希望をご記入ください...',
      sending: '送信中...',
      submit: '予約リクエストを送信',
      namePlaceholder: 'お名前',
    },
    footer: {
      info: 'iSmileについて',
      services: '歯科サービス',
      infoLinks: ['診療内容', '医師チーム', '院内設備', '診療予約'],
      serviceLinks: ['インプラント', '審美歯科', 'ポーセレンベニア', '審美クラウン', '矯正歯科', '小児歯科'],
    },
  },
  zh: {
    nav: { home: '首页', services: '服务', doctors: '医生团队', facility: '诊所环境', booking: '预约' },
    common: {
      hotline: '热线',
      bookNow: '立即预约',
      bookVisit: '预约就诊',
      chooseSchedule: '选择时间',
      contactUs: '联系我们',
      address: '地址',
      phone: '电话',
      email: '邮箱',
      openingHours: '营业时间',
      themeLight: '浅色模式',
      themeDark: '深色模式',
      language: '语言',
    },
    hero: {
      badge: 'iSmile 牙科诊所',
      title: '清晰、温和、贴心的牙科护理体验。',
      desc: 'iSmile 结合专注负责的医生、现代设备和真实诊所影像，让顾客在治疗前更安心。',
      explore: '查看服务',
      promises: ['现代设备', '清晰治疗方案', '个性化护理'],
      stats: [
        { value: '15+', label: '年经验' },
        { value: '5,000+', label: '顾客' },
        { value: '30分钟', label: '预约确认' },
      ],
    },
    campaign: {
      eyebrow: '活动与反馈',
      title: '真实的 iSmile 时刻，让信任更具体。',
      desc: '公益项目、儿童活动和治疗反馈，以明亮易读的节奏呈现。',
      labels: { community: '公益', event: '活动', feedback: '反馈', result: '前后对比', space: '空间', treatment: '治疗' },
      moments: '个瞬间',
      chooseImage: '选择图片',
      prev: '上一张',
      next: '下一张',
      pause: '暂停轮播',
      play: '播放轮播',
      book: '预约咨询',
      typeCopy: {
        community: {
          kicker: '公益项目',
          title: '重拾笑容计划',
          desc: '帮助需要恢复咀嚼能力和自信的顾客，呈现真实的支持故事。',
        },
        event: {
          kicker: '儿童活动',
          title: '儿童笑容日',
          desc: '明亮的活动画面，包含检查、礼物和适合家庭的牙科护理。',
        },
        feedback: {
          kicker: '真实顾客反馈',
          title: 'iSmile 的真实时刻',
          desc: '诊所里的真实照片让网站更自然、更亲切，也更值得信任。',
        },
        result: {
          kicker: '治疗效果',
          title: '笑容护理前后对比',
          desc: '直观看到美学牙科治疗后牙齿颜色的改善。',
        },
        space: {
          kicker: '诊疗空间',
          title: '真实治疗室',
          desc: '展示诊所环境和顾客护理过程中使用的设备。',
        },
        treatment: {
          kicker: '保守治疗',
          title: '温和根管治疗',
          desc: '突出细致咨询、现代技术和保留真牙理念的宣传内容。',
        },
      },
    },
    experience: {
      eyebrow: 'iSmile 体验',
      title: '快速预约、流程清楚，每一步都有团队引导。',
      desc: '从初步咨询到预约确认，iSmile 让流程更简单，帮助顾客在到店前就更安心。',
      steps: [
        { title: '贴心咨询', desc: '先了解需求，再建议合适的服务。' },
        { title: '快速安排', desc: '选择方便的时间，并尽快确认。' },
        { title: '透明治疗', desc: '医生说明方案、费用和预计时间。' },
      ],
      quickAction: '快速支持',
      quickTitle: '几分钟内完成预约',
    },
    services: {
      eyebrow: '特色服务',
      title: '牙科方案清晰呈现，帮助你更自信地选择。',
      featured: '推荐治疗',
      contact: '联系我们',
      from: '起',
      million: '百万越盾',
      bookThis: '预约此服务',
      book: '预约',
    },
    doctors: {
      eyebrow: '医生团队',
      title: '两位主诊医生，紧密跟进每一份治疗计划。',
      desc: 'Lê Nhi 医生和 Anh Dũng 医生直接咨询、跟进进度，并让每次就诊更舒适。',
      experience: '年经验',
      bookWith: '预约医生',
      choose: '选择此医生',
      spotlight: '主诊医生',
    },
    facility: {
      eyebrow: '诊所环境',
      title: '明亮、洁净，并为每次治疗细心准备的诊疗空间。',
      desc: '真实照片展示 iSmile 的治疗室、接待区和正在使用的设备。',
      cards: [
        { title: '现代治疗室', desc: '进口设备、严格消毒和整洁流程。' },
        { title: '接待空间', desc: '就诊前舒适、干净、便利的等候区域。' },
        { title: '真实顾客时刻', desc: '真实画面让 iSmile 的体验更亲切、更可信。' },
      ],
      lobbyAlt: 'iSmile 牙科诊所全景',
    },
    bookingPage: {
      steps: ['填写信息', '选择服务', '确认预约'],
      badge: '在线预约',
      title: '选择合适时间，iSmile 会尽快为你确认。',
      desc: '留下必要信息，我们的团队会确认时间并提醒就诊前准备事项。',
      privacy: '预约信息仅用于 iSmile 咨询和确认预约。',
    },
    bookingForm: {
      successTitle: '预约已提交！',
      successDesc: 'iSmile 已收到信息。团队会尽快联系确认预约。',
      another: '再次预约',
      eyebrow: '预约表单',
      title: '预约信息',
      desc: '填写一次，iSmile 将回电确认。',
      fullName: '姓名 *',
      phone: '电话号码 *',
      service: '服务',
      doctor: '医生',
      date: '就诊日期 *',
      time: '就诊时间 *',
      note: '备注',
      servicePlaceholder: '选择服务',
      doctorPlaceholder: '选择医生',
      notePlaceholder: '描述症状或特殊需求...',
      sending: '发送中...',
      submit: '提交预约请求',
      namePlaceholder: '你的姓名',
    },
    footer: {
      info: '关于 iSmile',
      services: '牙科服务',
      infoLinks: ['牙科服务', '医生团队', '诊所环境', '预约就诊'],
      serviceLinks: ['种植牙', '美容牙科', '瓷贴面', '美学牙冠', '正畸', '儿童牙科'],
    },
  },
  fr: {
    nav: { home: 'Accueil', services: 'Services', doctors: 'Médecins', facility: 'Clinique', booking: 'Rendez-vous' },
    common: {
      hotline: 'Hotline',
      bookNow: 'Réserver',
      bookVisit: 'Prendre rendez-vous',
      chooseSchedule: 'Choisir un horaire',
      contactUs: 'Nous contacter',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'Email',
      openingHours: 'Horaires',
      themeLight: 'Mode clair',
      themeDark: 'Mode sombre',
      language: 'Langue',
    },
    hero: {
      badge: 'Clinique dentaire iSmile',
      title: 'Des soins dentaires clairs, doux et personnalisés.',
      desc: 'iSmile réunit des médecins attentifs, des équipements modernes et de vraies images de la clinique pour rassurer chaque patient avant le traitement.',
      explore: 'Voir les services',
      promises: ['Équipements modernes', 'Plan de soin clair', 'Suivi personnalisé'],
      stats: [
        { value: '15+', label: 'ans d’expérience' },
        { value: '5 000+', label: 'patients' },
        { value: '30 min', label: 'confirmation' },
      ],
    },
    campaign: {
      eyebrow: 'Campagnes & Avis',
      title: 'Des moments réels d’iSmile qui inspirent confiance.',
      desc: 'Programmes communautaires, événements enfants et retours de traitement sont présentés dans une lecture lumineuse et fluide.',
      labels: { community: 'Communauté', event: 'Événement', feedback: 'Avis', result: 'Avant / après', space: 'Espace', treatment: 'Traitement' },
      moments: 'moments',
      chooseImage: 'Choisir l’image',
      prev: 'Image précédente',
      next: 'Image suivante',
      pause: 'Mettre en pause',
      play: 'Lancer',
      book: 'Réserver une consultation',
      typeCopy: {
        community: {
          kicker: 'Programme communautaire',
          title: 'Programme Sourire retrouvé',
          desc: 'Des histoires de soutien pour restaurer la mastication, le confort et la confiance.',
        },
        event: {
          kicker: 'Événement enfants',
          title: 'Journée du sourire enfant',
          desc: 'Un événement lumineux avec contrôle dentaire, cadeaux et soins adaptés aux familles.',
        },
        feedback: {
          kicker: 'Avis patient réel',
          title: 'Un moment réel chez iSmile',
          desc: 'Des photos prises à la clinique rendent le site plus chaleureux, naturel et crédible.',
        },
        result: {
          kicker: 'Résultat de soin',
          title: 'Avant et après esthétique',
          desc: 'Un aperçu direct de l’amélioration visible de la teinte des dents.',
        },
        space: {
          kicker: 'Espace clinique',
          title: 'Salle de soin réelle',
          desc: 'Une image concrète de l’espace et des équipements utilisés pendant les soins.',
        },
        treatment: {
          kicker: 'Soin conservateur',
          title: 'Traitement canalaire doux',
          desc: 'Des supports qui mettent en avant le conseil attentif, la technologie moderne et la préservation des dents.',
        },
      },
    },
    experience: {
      eyebrow: 'Expérience iSmile',
      title: 'Une réservation rapide, une visite claire et un accompagnement à chaque étape.',
      desc: 'De la première consultation à la confirmation, iSmile simplifie le parcours pour aider les patients à se sentir prêts.',
      steps: [
        { title: 'Conseil attentif', desc: 'Nous écoutons d’abord vos besoins avant de proposer le soin adapté.' },
        { title: 'Horaire rapide', desc: 'Choisissez un créneau pratique et recevez une confirmation rapidement.' },
        { title: 'Soin transparent', desc: 'Le médecin explique le plan, le coût et la durée prévue.' },
      ],
      quickAction: 'Support rapide',
      quickTitle: 'Réserver une visite en quelques minutes',
    },
    services: {
      eyebrow: 'Services phares',
      title: 'Des solutions dentaires présentées clairement pour choisir avec confiance.',
      featured: 'Traitement recommandé',
      contact: 'Nous contacter',
      from: 'À partir de',
      million: 'millions VND',
      bookThis: 'Réserver ce service',
      book: 'Réserver',
    },
    doctors: {
      eyebrow: 'Équipe médicale',
      title: 'Deux médecins principaux suivent chaque plan de traitement de près.',
      desc: 'Les docteurs Lê Nhi et Anh Dũng conseillent directement, suivent les progrès et rendent chaque rendez-vous plus confortable.',
      experience: 'ans d’expérience',
      bookWith: 'Réserver avec le médecin',
      choose: 'Choisir ce médecin',
      spotlight: 'Médecin référent',
    },
    facility: {
      eyebrow: 'Installations',
      title: 'Une clinique lumineuse, propre et préparée avec soin pour chaque traitement.',
      desc: 'Les images réelles montrent les salles de soin, l’accueil et les équipements utilisés chez iSmile.',
      cards: [
        { title: 'Salle de soin moderne', desc: 'Équipements importés, stérilisation stricte et flux de travail organisé.' },
        { title: 'Espace d’accueil', desc: 'Un espace propre et pratique avant la consultation.' },
        { title: 'Moments patients réels', desc: 'Des images vraies rendent l’expérience iSmile plus chaleureuse et crédible.' },
      ],
      lobbyAlt: 'Vue d’ensemble de la clinique dentaire iSmile',
    },
    bookingPage: {
      steps: ['Vos informations', 'Choisir le service', 'Confirmation'],
      badge: 'Réservation en ligne',
      title: 'Choisissez un créneau adapté et iSmile le confirmera rapidement.',
      desc: 'Laissez les informations essentielles et notre équipe confirmera l’horaire avec les conseils utiles avant la visite.',
      privacy: 'Les informations de réservation servent uniquement au conseil et à la confirmation chez iSmile.',
    },
    bookingForm: {
      successTitle: 'Demande envoyée !',
      successDesc: 'iSmile a bien reçu vos informations. Notre équipe vous contactera bientôt pour confirmer.',
      another: 'Prendre un autre rendez-vous',
      eyebrow: 'Formulaire',
      title: 'Détails du rendez-vous',
      desc: 'Remplissez une fois, iSmile vous rappellera pour confirmer.',
      fullName: 'Nom complet *',
      phone: 'Téléphone *',
      service: 'Service',
      doctor: 'Médecin',
      date: 'Date de visite *',
      time: 'Heure *',
      note: 'Note',
      servicePlaceholder: 'Choisir un service',
      doctorPlaceholder: 'Choisir un médecin',
      notePlaceholder: 'Décrivez les symptômes ou demandes particulières...',
      sending: 'Envoi...',
      submit: 'Envoyer la demande',
      namePlaceholder: 'Votre nom complet',
    },
    footer: {
      info: 'À propos d’iSmile',
      services: 'Services dentaires',
      infoLinks: ['Services dentaires', 'Équipe médicale', 'Installations', 'Prendre rendez-vous'],
      serviceLinks: ['Implants dentaires', 'Dentisterie esthétique', 'Facettes céramiques', 'Couronnes esthétiques', 'Orthodontie', 'Dentisterie enfants'],
    },
  },
};

const UiPreferencesContext = createContext(null);

function getStoredLanguage() {
  if (typeof window === 'undefined') return 'vi';
  const stored = window.localStorage.getItem('ismile-language');
  return LANGUAGE_OPTIONS.some((item) => item.code === stored) ? stored : 'vi';
}

function getStoredTheme() {
  if (typeof window === 'undefined') return 'light';
  return window.localStorage.getItem('ismile-theme') === 'dark' ? 'dark' : 'light';
}

function getPath(source, path) {
  return path.split('.').reduce((value, key) => value?.[key], source);
}

export function UiPreferencesProvider({ children }) {
  const [language, setLanguage] = useState(getStoredLanguage);
  const [theme, setTheme] = useState(getStoredTheme);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem('ismile-language', language);
  }, [language]);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.dataset.theme = theme;
    window.localStorage.setItem('ismile-theme', theme);
  }, [theme]);

  const value = useMemo(() => {
    const t = (path) => getPath(translations[language], path) ?? getPath(translations.vi, path) ?? path;

    return {
      language,
      setLanguage,
      theme,
      setTheme,
      toggleTheme: () => setTheme((current) => (current === 'dark' ? 'light' : 'dark')),
      t,
    };
  }, [language, theme]);

  return <UiPreferencesContext.Provider value={value}>{children}</UiPreferencesContext.Provider>;
}

export function useUiPreferences() {
  const context = useContext(UiPreferencesContext);
  if (!context) throw new Error('useUiPreferences must be used inside UiPreferencesProvider');
  return context;
}
